language: go

matrix:
  fast_finish: true
  include:
    - go: 1.11.x
      env: GO111MODULE=on
    - go: 1.12.x
      env: GO111MODULE=on
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.15.x
    - go: master

before_install:
  - go get -v ./...

install:
#  - go test -v -benchmem -bench . -coverprofile=coverage.txt -covermode=atomic
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
